version: '3.8'

services:
  # O serviço do seu banco de dados PostgreSQL
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: apikey123
      POSTGRES_DB: api_financeira
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # O serviço da sua aplicação FastAPI
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:apikey123@db:5432/api_financeira

volumes:
  db-data: